sqlplus sys as sysdba
-- 1. Cambiar a la base de datos conectable
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2. Crear el usuario (ejemplo: mi_usuario)
-- Nota: En 21c, si usas XEPDB1 no necesitas el prefijo C##
CREATE USER mi_usuario IDENTIFIED BY mi_password123;

-- 3. Darle permisos para conectarse y crear cosas
GRANT CONNECT, RESOURCE, DBA TO mi_usuario;

-- 4. Darle cuota de espacio (importante para que pueda guardar datos)
ALTER USER mi_usuario QUOTA UNLIMITED ON USERS;

CREATE USER prg2 IDENTIFIED BY PRG2 --nombre del proyecto 
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE TO PRG2;

-- Crear una tabla 
CREATE TABLE usuarios (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(50) NOT NULL,
    apellido        VARCHAR2(50) NOT NULL,
    email           VARCHAR2(100) UNIQUE,
    passw           VARCHAR2(100) NOT NULL, -- Espacio para el Hash
    fecha_creacion  DATE DEFAULT SYSDATE,
    estado          CHAR(1) DEFAULT 'A'    -- 'A' de Activo
);

-- Insertar un registro
INSERT INTO usuarios (nombre, apellido, passw) VALUES ('Richard', 'Steven', 'jacksparrow');

-- Confirmar los cambios COMMIT;


SELECT id_usuario 
FROM usuarios 
WHERE nombre = 'Richard' 
AND passw = LOWER(RAWTOHEX(STANDARD_HASH('jacksparrow', 'SHA256')));

SELECT * FROM usuarios;

-- Ajusta el ancho de la línea para que no salte de renglón
SET LINESIZE 200;

-- Ajusta el número de filas antes de repetir el encabezado
SET PAGESIZE 50;

-- Ajusta el ancho visual de columnas específicas (opcional)
COLUMN nombre FORMAT A15;
COLUMN apellido FORMAT A15;
COLUMN passw FORMAT A30;

-- Ahora lanza el select
SELECT * FROM usuarios;